logging:
  file: 
    name: target/logs/local_profile_app.log
  level:
    org.springframework.web: INFO
    org.com.ps.nextgen: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO

server:
  port: 8000
  
spring:
  application:
    name: employee-common-model
  data:
    mongodb:
     database: employee-records
     uri: mongodb://localhost:27017
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: shubh123456
    url: jdbc:mariadb://localhost:3306/mockproject
    username: root

service:
    employee-management: http://localhost:8088

